name: Auto-Save RSVP
on:
  repository_dispatch:
    types: [simpan-ucapan]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Database
        run: |
          mkdir -p database
          ID="${{ github.event.client_payload.project_id }}"
          FILE="database/data-${ID}.json"
          if [ ! -f "$FILE" ]; then echo "[]" > "$FILE"; fi
          jq ". += [${{ toJson(github.event.client_payload.data) }}]" "$FILE" > tmp.json && mv tmp.json "$FILE"
      - name: Commit & Push
        run: |
          git config --global user.name "Bot-Undangan"
          git config --global user.email "bot@github.com"
          git add database/
          git commit -m "RSVP baru masuk"
          git push
          
